DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL DEFAULT '',
    last_name VARCHAR(50) NOT NULL DEFAULT '',
    email VARCHAR(100) NOT NULL DEFAULT '',
    age INT NOT NULL DEFAULT 0,
    address VARCHAR(100) NOT NULL DEFAULT '',
    joining_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)